<?php
$listarray = array ( array ( 'label' => 'Nr',
                             'width' => 50, 
                             'type' => 'nummer',
                             'dbfield' => 'dummy' ),
                     array ( 'label' => 'Stadtteil',
                             'name' => 'stadtteil', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldstadtteil' ),
                     array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldname' ),
                     array ( 'label' => 'Adresse',
                             'name' => 'adresse', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldadresse' ),
                     array ( 'label' => 'X-Koor',
                             'name' => 'xkoor', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldxkoor' ),
                     array ( 'label' => 'Y-Koor',
                             'name' => 'ykoor', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldykoor' ));

$filterarray = array ( array ( 'label' => 'Stadt:',
                               'name' => 'stadt', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblorte',
                               'seldbfield' => 'fldbez',
                               'dbfield' => 'fldstadt' ),
                       array ( 'label' => 'Stadtteil:',
                               'name' => 'stadtteil', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblstadtteil',
                               'seldbfield' => 'fldbez',
                               'selorder' => 'fldbez',
                               'dbfield' => 'fldstadtteil' ));


$pararray = array ( 'headline' => 'Defribillatoren',
                    'dbtable' => 'tbldefribilatoren',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>