<?php
$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'bez', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldbez' ),
                     array ( 'label' => 'Name',
                             'name' => 'name', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldname' ),
                     array ( 'label' => 'PHP-Code',
                             'name' => 'phpcode', 
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldphp' ),
                     array ( 'label' => 'Menu-ID',
                             'name' => 'menuid', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'dbtable' => 'tblmenu_liste',
                             'seldbfield' => 'fldmenu',
                             'seldbindex' => 'fldindex',
                             'seldbwhere' => '',
                             'dbfield' => 'fldmenuid' ),
                     array ( 'label' => 'Target',
                             'name' => 'target', 
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldtarget' ),
                     array ( 'label' => 'Parameter',
                             'name' => 'param', 
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldparam' ),
                     array ( 'label' => 'Typ',
                             'name' => 'typ', 
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldtyp' ),
                     array ( 'label' => 'Aktiv',
                             'name' => 'aktiv', 
                             'width' => 20, 
                             'type' => 'YN',
                             'dbfield' => 'fldaktiv' ),
                     array ( 'label' => 'Version',
                             'name' => 'version', 
                             'width' => 10, 
                             'type' => 'select',
                             'dbtable' => 'tblversion',
                             'seldbfield' => 'fldkurz',
                             'dbfield' => 'fldversion' ));
//                     array ( 'label' => '',
//                             'width' => 5, 
//                             'type' => 'icon',
//                             'func' => 'mysqlcopyremote.php',
//                             'dbfield' => 'icon-share' ));

$filterarray = array ( array ( 'label' => 'Parent',
                             'name' => 'parent', 
                             'width' => 10, 
                             'type' => 'selectid',
                             'sign' => '=',
                             'dbtable' => 'tblmenu_liste',
                             'seldbfield' => 'fldmenu',
                             'seldbindex' => 'fldindex',
                             'dbfield' => 'fldmenuid' ));

$pararray = array ( 'headline' => 'Funktionen ',
                    'dbtable' => 'tblfunc',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>