<?php
$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 50, 
                             'type' => 'text',
                             'dbfield' => 'fldname' ),                     
                     array ( 'label' => 'Stadtbezirk',
                             'name' => 'bez', 
                             'width' => 500, 
                             'type' => 'text',
                             'dbfield' => 'fldstadtbezirk'), 
                     array ( 'label' => 'Adresse',
                             'name' => 'adresse',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldaddress' ),
                     array ( 'label' => 'X-Koor',
                             'name' => 'xkoor',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldxkoor' ),
                     array ( 'label' => 'Y-Koor',
                             'name' => 'ykoor',
                             'width' => 10, 
                             'type' => 'text',
                             'dbfield' => 'fldykoor' ),
                     array ( 'label' => 'Type',
                             'name' => 'type',
                             'fieldhide' => 'true', 
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldtype' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'singlegooglemap.php',
                             'dbfield' => 'icon-book' ) );

$filterarray = array ( 
                       array ( 'label' => 'Stadtbezirk:',
                               'name' => 'stadtbezirk', 
                               'width' => 10, 
                               'type' => 'select',
                               'sign' => '=',
                               'dbtable' => 'tblstadtbezirk',
                               'seldbfield' => 'fldbez',
                               'dbfield' => 'fldstadtbezirk' ));


$pararray = array ( 'headline' => 'Spielpl&aumltze',
                    'dbtable' => 'tblmarkers',
                    'orderby' => '',
                    'strwhere' => '',
                    'fldindex' => 'fldindex');
?>