<?php
$listarray = array ( array ( 'label' => 'Bezeichnung',
                             'name' => 'bez',
                             'width' => 100, 
                             'type' => 'text',
                             'dbfield' => 'fldBez' ),
                     array ( 'label' => 'Barcode',
                             'name' => 'barcode',
                             'width' => 100, 
                             'fieldhide' => 'false',
                             'type' => 'text',
                             'dbfield' => 'fldBarcode' ),
                     array ( 'label' => 'Mindest',
                             'name' => 'mindest',
                             'fieldhide' => 'true',
                             'width' => 100, 
                             'type' => 'ref',
                             'dbtable' => 'tblvorrat',
                             'seldbfield' => 'fldmindestmenge',
                             'seldbreffld' => 'fldv01barcode',
                             'dbfield' => 'fldBarcode' ),
                     array ( 'label' => 'Kaufort',
                             'name' => 'kaufort',
                             'width' => 100, 
                             'type' => 'select',
                             'dbtable' => 'tblorte',
                             'seldbfield' => 'fldBez',
                             'dbfield' => 'fldOrt' ),
                     array ( 'label' => 'Abteilung',
                             'name' => 'abteilung',
                             'width' => 100, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblabteilung',
                             'seldbfield' => 'fldAbteilung',
                             'dbfield' => 'fldAbteilung' ),
                     array ( 'label' => 'Konto',
                             'name' => 'konto',
                             'width' => 20, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblktokonten',
                             'seldbfield' => 'fldKurz',
                             'dbfield' => 'fldKonto' ),
                     array ( 'label' => 'Typ',
                             'name' => 'typ',
                             'width' => 20, 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblstamm_typ',
                             'seldbfield' => 'fldTyp',
                             'dbfield' => 'fldTyp' ),
                     array ( 'label' => 'Anz',
                             'name' => 'anz',
                             'fieldhide' => 'true',
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldAnz' ),
                     array ( 'label' => 'Preis',
                             'name' => 'preis',
                             'width' => 20, 
                             'type' => 'text',
                             'dbfield' => 'fldPreis' ),
                     array ( 'label' => '',
                             'width' => 5, 
                             'type' => 'icon',
                             'func' => 'setfield.php',
                             'funcpara' => 'dbfield=fldTyp&dbwert=WARE',
                             'dbfield' => 'icon-book' ));

$filterarray = array ( array ( 'label' => ' Kaufort',
                             'name' => 'kaufort', 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblorte',
                             'selwhere' => "fldo01typ='FREMD'",
                             'seldbfield' => 'fldBez',
                             'dbfield' => 'fldOrt' ),
                       array ( 'label' => ' Typ',
                             'name' => 'typ', 
                             'type' => 'select',
                             'sign' => '=',
                             'dbtable' => 'tblstamm_typ',
                             'selwhere' => '',
                             'seldbfield' => 'fldTyp',
                             'dbfield' => 'fldTyp' ));


$pararray = array ( 'headline' => 'Stammdaten',
                    'dbtable' => 'tblartikel',
                    'orderby' => 'fldOrt,fldBez',
                    'strwhere' => '',
                    'fldindex' => 'fldIndex',
                    'markbgcolor' => '88ff88',
                    'ummarkbgcolor' => 'ffffff',
                    'marksuccess' => '0',
                    'marksign' => '>',
                    'markfield' => 'fldAnz');
                    
?>